### ISSUE TITLE
Tab/Folding Problem

### ISSUE THREAD

**Issue by andyl** [vimoutliner/vimoutliner#114]
In insert mode, sometimes the tab character closes the parent fold.  

To reproduce - starting in normal mode: `ggo<tab>`

This jumps to the first line, opens a new line for editing, then inserts a tab indent.  BUT is also folds the parent.

The command `:verbose map <tab>` shows no key assignments.  I've disabled snipmate.  Can anyone offer a clue or ideas on how to debug this problem?  Thanks in advance!

**Comment by mcepl** [comment]
I don’t understand.
> To reproduce - starting in normal mode: ggo<tab>
Is the file empty or not? If it is, then you make a new level item and it is properly folded. What's the problem?
If the file is not empty, then you just add one subordinate item to the root. I don't see there a problem either.
Please, explain what's the problem and provide exact steps leading to the issue, and then describe what you have expected and what actually happened to make me understand what's the problem, please.
Meanwhile, I am closing this issue, but I am very ready to reopen if I get the reproduction steps. Thank you.

**Comment by andyl** [comment]
Thanks for your reply.  To reproduce:
1) start with an empty file `vim newfile.otl`
2) type `:set invlist<cr>iline 1.1<cr><tab>`

Notes:
- `:set invlist<cr>` displays non-printing characters (`$` for `newline`, `^I` for `tab`)
- after I type `<tab>`, vim folds on `line 1.1`, and remains in insert mode
- to unfold and continue: `<esc>zOA`

Perhaps this problem is due to some other vim setting.  Have looked at non-printing characters, `<tab>` keymaps (there are none), tried disabling all other plugins. I'm somewhat new to Vim and not sure how to diagnose / debug this issue from here...

**Comment by mcepl** [comment]
Sorry, but this is exactly the expected beahvior ... this is vim'''outliner''', we want vim to behave like with outline.

**Comment by andyl** [comment]
The behavior I see is inconsistent.  It auto-collapses after the first header, but does not auto-collapse after lower headers.  Check out the attached gif - hopefully that will show the problem a little more clearly.

![vim_test](https://cloud.githubusercontent.com/assets/90030/7717995/1879101a-fe5f-11e4-8ad8-756daff28290.gif)

**Comment by andyl** [comment]
I found that the problem was due to a vim setting: `setlocal foldlevel=0` - something I used to open an outline with all headers collapsed.  Once I removed that setting, everything was OK.

**Comment by mcepl** [comment]
Two questions to make sure we are on the same page:
 * that `setlocal foldlevel=0` was your doing in some of your configuration files, not something VO did, right?
 * this auto-folding is something done by the vim itself, right? It is not something we did (yes, I can reproduce this as well with `setlocal foldlevel=0`) by some other plugin, right?
@noelhenson , do you think this is a bug in `vim` itself?

**Comment by andyl** [comment]
Yes I had `setlocal foldlevel=0` in a one of my vim config files (~/.vim/after/ftplugin/votl.vim) because I wanted the outlines to be closed by default.

The autofolding is done by vim itself or by VO - I'm not sure which.  I did a test to disable all other plugins and still had the autofolding problem.

**Comment by mcepl** [comment]
First of all, I don't understand why I closed this.
