### ISSUE TITLE
Searching with \w in pattern is broken

### ISSUE THREAD

**Issue by cche** [vimoutliner/vimoutliner#117]
Whenever I issue a \w in a search pattern (/ or ?) I'm pulled back to the buffer in insert mode. I can not complete the search pattern.

This has broken custom mappings that I used regularly.

Hope you can fix it.
Thanks,
Cristian

Mac os X, using macvim installed from homebrew.

**Comment by mcepl** [comment]
Cannot reproduce with 7.4.160 on Linux. `\w` doesn’t do any nasty things to my outliner. Could I get output of `:version` command here, please?

**Comment by cche** [comment]
The first lines of :version output are:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug  6 2015 11:13:22)
MacOS X (unix) version
Included patches: 1-769
Compiled by Homebrew

I use \ as leader and when typing \w while searching, the file gets saved and put into insert mode as if ,,w was called. Maybe this helps!
Cheers,
Cristian

**Comment by mcepl** [comment]
'The leader' is the key. Yes, `<leader>w` in the search mode leads to Insert mode. Weird.

**Comment by cche** [comment]
Hi,
<leader>w is working as expected in search mode with the changes made.
Sorry for the delay in responding, urgencies took over :-)

Thanks!
Cristian

**Comment by mcepl** [comment]
Thank you for letting me know.
