### ISSUE TITLE
Miscalculated times (clock plugin)

### ISSUE THREAD

**Issue by freeit** [vimoutliner/vimoutliner#123]
When I'm using clocking on lines with a checkbox, time is calculated incorrect, e.g.:

```
[X] Project 1
    [X] Brainstorming 2015-12-15 [15:00:00 -- 16:00:00] -> 16.00 h
```
I've testet with vimoutliner from the master branch and the version tagged with 0.4.0 .

**Comment by linxichen** [comment]
I encounter this problem too. Please fix.

**Comment by mcepl** [comment]
@noelhenson any idea?

**Comment by noelhenson** [comment]
I can take a look. I do remember these issues being mentioned before but since I didn't not create the clock plugin I didn't put any effort into it. I will take a look at it.

**Comment by linxichen** [comment]
Thanks man!

Best,
Linxi Chen

**Comment by noelhenson** [comment]
OK. It took a while to get the plugin running in my non-standard setup (I know, Matej. I know.)
It appears to be a greedy matching issue with the regex that selects the time fields from the heading. The checkbox is interfering.

I'm not the regex/vimscript guru that people think I am. Any help with this would be appreciated.

**Comment by noelhenson** [comment]
Once we fix this, the negative times from midnight crossings can easily be fixed.

**Comment by mcepl** [comment]
> I'm not the regex/vimscript guru that people think I am. Any help with this would be appreciated.
Perhaps just
```
:he non-greedy
```
?

**Comment by noelhenson** [comment]
Of course that. But the specifics were what I was after. Anyway, I have a fix. I'm just refreshing my memory on the branch and pull for VO.

**Comment by noelhenson** [comment]
The fix is complete for the times fields regex and for negative times due to midnight crossings. If the end time is less than the start time, a midnight crossing is assumed and compensated for. I believe the pull request for this fix should be available.

**Comment by mcepl** [comment]
Fixed! Thank you, @noelhenson !
