### ISSUE TITLE
VOput broken?

### ISSUE THREAD

**Issue by frioux** [vimoutliner/vimoutliner#124]
I'm sure that there is some kind of conflict with another of my many plugins.  If I do `yyp` to copy a line, the `p` does nothing.  I don't know much about vimscript, but I am happy to try anything you can recommend to me to debug the issue more and either get it fixed or fix my setup.

Thanks

**Comment by jostber** [comment]
On 25.01.16,09:35, fREW Schmidt wrote:
>I'm sure that there is some kind of conflict with another of my many plugins.  If I do `yyp` to copy a line, the `p` does nothing.  I don't know much about vimscript, but I am happy to try anything you can recommend to me to debug the issue more and either get it fixed or fix my setup.

Does this work in an ordinary vim file?

**Comment by frioux** [comment]
paste?  Yes.

On Tue, Jan 26, 2016 at 10:09 AM, Jostein Berntsen <notifications@github.com
> wrote:

> On 25.01.16,09:35, fREW Schmidt wrote:
> >I'm sure that there is some kind of conflict with another of my many
> plugins. If I do `yyp` to copy a line, the `p` does nothing. I don't know
> much about vimscript, but I am happy to try anything you can recommend to
> me to debug the issue more and either get it fixed or fix my setup.
>
> Does this work in an ordinary vim file?
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vimoutliner/vimoutliner/issues/124#issuecomment-175148060>
> .
>



-- 
fREW Schmidt
http://blog.afoolishmanifesto.com

**Comment by jostber** [comment]
On 26.01.16,10:17, fREW Schmidt wrote:
>paste?  Yes.
>
>On Tue, Jan 26, 2016 at 10:09 AM, Jostein Berntsen <notifications@github.com
>> wrote:
>
>> On 25.01.16,09:35, fREW Schmidt wrote:
>> >I'm sure that there is some kind of conflict with another of my many
>> plugins. If I do `yyp` to copy a line, the `p` does nothing. I don't know
>> much about vimscript, but I am happy to try anything you can recommend to
>> me to debug the issue more and either get it fixed or fix my setup.
>>
>> Does this work in an ordinary vim file?
>>

It works in my setup so it is probably some conflicting plugin here. Does
":map yyp" and ":map p" show you anything?

**Comment by frioux** [comment]
Oh wow, I do have maps for those:

`:map yyp` shows:

```
  y           * y`]
```

`:map p` shows:

```
n  p           *
p`]

v  p
<SNR>10_Repl()

```

I'll look at disabling those and seeing if that helps I guess

On Tue, Jan 26, 2016 at 10:31 AM, Jostein Berntsen <notifications@github.com
> wrote:

> On 26.01.16,10:17, fREW Schmidt wrote:
> >paste? Yes.
> >
> >On Tue, Jan 26, 2016 at 10:09 AM, Jostein Berntsen <
> notifications@github.com
> >> wrote:
> >
> >> On 25.01.16,09:35, fREW Schmidt wrote:
> >> >I'm sure that there is some kind of conflict with another of my many
> >> plugins. If I do `yyp` to copy a line, the `p` does nothing. I don't
> know
> >> much about vimscript, but I am happy to try anything you can recommend
> to
> >> me to debug the issue more and either get it fixed or fix my setup.
> >>
> >> Does this work in an ordinary vim file?
> >>
>
> It works in my setup so it is probably some conflicting plugin here. Does
> ":map yyp" and ":map p" show you anything?
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vimoutliner/vimoutliner/issues/124#issuecomment-175162109>
> .
>



-- 
fREW Schmidt
http://blog.afoolishmanifesto.com

**Comment by mcepl** [comment]
OK, let's call it PEBKAC for now and close. Feel free to tell me if you have reasons to believe that this is VO problem.

**Comment by frioux** [comment]
Never found out what the cause of this was, but just disabled the paste plugin and am willing to type ]p myself (which works.)

**Comment by noelhenson** [comment]
Can we get a description of the problem and perhaps steps for 
reproduction so we have a chance to resolve the issue?

**Comment by frioux** [comment]
Sure I'll give you some steps. Will send you something in a few hours.

-- 
sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment]
Ok so this is pretty weird but here's the deal.  I installed [Sneak](https://github.com/justinmk/vim-sneak) a while ago, and then uninstalled it.  I have the following in my vimrc:

```
map : <Plug>SneakNext
```

Because I have ; and : swapped.  Interestingly, this is the only plugin that has an issue with the above.  I'm removing the above since I don't have that plugin anymore anyway, but somehow VOTL was confused by it where other things are not.  Let me know if you need more details.
