### ISSUE TITLE
Sorting top level tree

### ISSUE THREAD

**Issue by danielcnorris** [vimoutliner/vimoutliner#125]
Looks like ,,s and ,,S currently only work on subtrees. Running :sort on the entire tree destroys the hierarchical tree structure. I currently sort my top level by placing it in a subtree under a temporary top-level header, sorting the now second level headers, and then deleting the temporary top-level header. Is there a way to sort top level nodes while preserving the nested hierarchical structure directly?

**Comment by mcepl** [comment]
sorry, test

**Comment by jostber** [comment]
On 26.01.16,08:09, Daniel Norris wrote:
>Looks like ,,s and ,,S currently only work on subtrees Running :sort on the entire tree destroys the hierarchical tree structure I currently sort my top level by placing it in a subtree under a temporary top-level header, sorting the now second level headers, and then deleting the temporary top-level header Is there a way to sort top level nodes while preserving the nested hierarchical structure directly?
>

The sort function in vimoutliner is a sortchildren() function. To get the
functionality you want you might write a short vim function to make a
temporary indent, then call sortchildren and then de-indent?

**Comment by danielcnorris** [comment]
Yeah that's what I'm doing. Just wanted to check that this was expected behavior. I think a good default would be to have ,,s and ,,S also sort top level items while preserving outline structure.

Thanks for your response!

**Comment by mcepl** [comment]
@danielcnorris Could we by chance get that improved sorting as a merge request here?

**Comment by danielcnorris** [comment]
@mcepl I actually moved away from using vimoutliner since opening this, so I never implemented. Great plugin.
