### ISSUE TITLE
remove intrusive <C-K> and <C-N> mappings

### ISSUE THREAD

**Issue by leoroos** [vimoutliner/vimoutliner#128]
In general I think it is bad behavior to force the end user to use a specific mapping, especially with vim, where a configuration can load tens of plugins to provide all the user desired functionality.

the `ftplugin/votl.vim` contains an array of mappings. Most of them use `<localleader>` and can at least be indirectly configured. But the [mappings](https://github.com/vimoutliner/vimoutliner/blob/master/ftplugin/votl.vim#L648-L649)

    map <silent><buffer>   <C-K>         <C-]>
    map <silent><buffer>   <C-N>         <C-T>

are global and use up two easily accessible and therefore more likely already user defined mappings. Apart from having already not much worse default mappings. A typical use might be for example to use them to jump between multiple split windows as described on [vim.wikia.com](http://vim.wikia.com/wiki/Switch_between_Vim_window_splits_easily).

Could we please remove at least those. It is a quick and easy fix and it is easy enough to mention additional mappings in the doc that the user can then add himself to his `.vimrc`. In any case the user has to go through the doc to see which mappings are available.

I will add a pull request for this shortly.

**Comment by mcepl** [comment]
Fixed by #129 (commit 72c138d). Thank you!

**Comment by leoroos** [comment]
Thank you! :)
Though I was a little overzealous with my deletions and deleted by accident also the internal mappings
which don't interfere with the user mappings, see #130
