### ISSUE TITLE
Hoisting not working for me, how to find log/debug info?

### ISSUE THREAD

**Issue by linxichen** [vimoutliner/vimoutliner#131]

**Comment by linxichen** [comment]
Error message 
E216: No such group or event: filetypedetect *

it seems to come from conflict of system built-in vim by Mac OS El Capitan and my homebrew installed vim 7.4

any idea how to fix this?

**Comment by noelhenson** [comment]
A little more information on the failure and steps to reproduce it would 
be helpful.

**Comment by linxichen** [comment]
I got a little confused by the doc "votl.txt"

it seems <localleader>hh instead of <localleader>h is the right way to activate hoisting?
Also the hosting behavior i got from hh is different from the doc describes (no new otl file is created, saving changes doesn't revert to the original tree etc.)

may be that's the behavior of new hoist instead and the votl.txt is describing the old one?

**Comment by noelhenson** [comment]
LInxichen,

Again, we are short on details here. I will have to guess.

I did a ":map" on my installation. Is shows these commands for hoisting:

    ,,hD         @:call DeHoistAll()<CR>

    ,,hd         @:call DeHoist()<CR>

    ,,hh         @:call Hoist(line("."))<CR>

I believe the VO help files need some work to be up to date with all the 
plugins.

Hoisting is an experimental feature that has never worked the way I 
wanted it to. I worked on it for a long time and could never get it to 
be robust and reliable. Use it at your own risk.

If you would like to see the intermediate files, you can put:

let g:hoistParanoia=1

into your .vimrc file or in vim's config lines.

Noel

**Comment by mcepl** [comment]
@linxichen What is the status of this bug, please?

**Comment by mcepl** [comment]
Sorry, @linxichen , feel free to reopen with additional information, if you feel it should be alive.
