### ISSUE TITLE
installation from .zip

### ISSUE THREAD

**Issue by KingEdwardI** [vimoutliner/vimoutliner#133]
I just spent about two hours trying to figure out why VO wasn't working at all. I installed the file from the .zip and it wouldn't work, so I removed the folder from ~/.vim and installed via Pathogen. this didn't work either. After hours of tweaking settings and uninstalling/reinstalling, but nothing seemed to work. It turns out that the original install from the .zip included a 'filetype.vim' into the ~/.vim folder. This broke all filetype settings. Removing that fixed everything.
Mostly a cautionary tale to only install things via Pathogen.

**Comment by mcepl** [comment]
You are right, we should fix the README.

I guess, Steve willl complain, but we should make it clear that ``pathogen``-like installation is the preferred method.

**Comment by noelhenson** [comment]
Lots of the documentation needs to be gone through. Perhaps that could 
be 0.5 goal.

**Comment by edvetterdrake** [comment]
There was also the issue with the comma-comma commands on Mac. It seems I have to add default settings to the user created .vimoulinerrc. In the default rc it says to just uncomment them, but that did nothing. Now that it's pretty much working, I love it.

**Comment by noelhenson** [comment]
Out of curiosity, what did you do to finally get it working?

**Comment by KingEdwardI** [comment]
After uninstalling all of the install.sh files, I had to move all of the default rc commands into the user created ~/.vimoutlinerrc. also had to change the line shift command from 
`dd <up>P` -> `dd <Up> P`

**Comment by mcepl** [comment]
@noelhenson I see two problems:

1. particular one, that there shouldn't be a whole ``filetype.vim``, but just a snippet in ``~/.vim/ftdetect/`` subdirecotry for the zip-based installation
2. that we should keep the zip-based Steve’s installation around at all. We should really switch everybody to ``pathogen``-like style, which Just Works™.

**Comment by noelhenson** [comment]
Can you explain #1 a bit more?

For #2, perhaps we shouldn't keep the zip installation around. It's been 
something like 15 years (perhaps more?) that those zips were created. 
Perhaps we could add what the contents were to the docs somewhere in 
case it is ever needed and leave it at that.

**Comment by mcepl** [comment]
> Can you explain 1. a bit more?

``he :ftdetect`` (the appropriate file is already present in the repo).

**Comment by mcepl** [comment]
I think this discussion is getting increasingly silly. Please, comment on #147 and we move on with this.
