### ISSUE TITLE
filetype .otl not detected when opening files from CLI

### ISSUE THREAD

**Issue by JervisTetch** [vimoutliner/vimoutliner#136]
When opening files like `vim file.otl` or `vim -p file.otl file2.otl [...]` the filetype .otl isn't detected by vim. Doing `:e` after opening file from CLI or opening the file directly in vim does solve this problem.

Is there probably a workaround for this?

**Comment by JervisTetch** [comment]
Ok, i found a solution for my special case. Opening files like `vim -p file.otl file2.otl [...] -c "tabdo e | tabfirst` does it.

**Comment by mcepl** [comment]
@JervisTetch how did you install vimoutliner? Manually copying files to your ~/.vim or do you use some plugin mechanism (vundle, plug, vim8 packages)?

**Comment by JervisTetch** [comment]
I've installed VO via Vundle and `~/.vim/ftdetect/votl.vim` exists but differs from the actual git version.
```
$ wget https://raw.githubusercontent.com/vimoutliner/vimoutliner/master/ftplugin/votl.vim -q
$ md5sum ~/.vim/ftdetect/votl.vim votl.vim                                                 
efbbefa314547353462086dc50f170b1  /home/jervis/.vim/ftdetect/votl.vim
d22237f6221f811754077c2eabfc9989  votl.vim
```

I've checked the HEAD of my git repo because I haven't installed any updates for a while.

Here's the diff:
[votl.vim.txt](https://github.com/vimoutliner/vimoutliner/files/1565806/votl.vim.txt)


```
$ git rev-parse HEAD
c13141d604959d84225c3a53dc4b0ef5ae8b2bfe
```

**Comment by mcepl** [comment]
OK, I call this ``NOTABUG`` and closing. If you have any problems with that, please, reopen and explain me what should be done here.
