### ISSUE TITLE
Question: Default leader is "\" but documented is ",,"

### ISSUE THREAD

**Issue by xkpd3** [vimoutliner/vimoutliner#139]
Hello,
The leader key "\" is set as default. But in the documentation, votl_cheatsheet etc. the ",," comma comma leader is documented.

Shouldn't the documentation reflect the default? I'm happy to work on that if this is wanted.

**Comment by noelhenson** [comment]
Stefan,

Please do. All help is appreciated.

Noel

**Comment by mcepl** [comment]
We had couple of bitter fights over this. @noelhenson  and Steve Litt (the original author of VO) prefer ``,,``. I thought that not changing ``maplocalleader`` from its default value would make users more confused than anything. If you would like to switch to ``,,``, just comment the appropriate line in ``vimoutlinerrc`` and everything should be fine.

**Comment by noelhenson** [comment]
I don't know if 'bitter' is the appropriate word. ;) We are all smart 
people with our own ways of doing things. And I have great respect for 
you have done, Matej.

:D

**Comment by xkpd3** [comment]
It's not about my personal settings. I already switched back to ",,".

I don't really care about what's the default. "\" for me is bad, because on a German keyboard layout, this is ALT_R + the key right of "0". This is an uncomfortable key combo.

However, I really had a hard time to find this setting. I have installed the plugin and it took me quite some time to figure out why ",," did not work. At first I thought my installation is wrong, because everywhere ",," is documented and it was not working.

I mean... what's the first thing YOU do after installing a plugin? You read the docs and play around with it before checking configuration options, right?

After I read the `vimoutlinerrc` and saw the setting, it was clear to me..

I care about that the documentation reflects the default.

So I will move on and change the documentation to "\" and add comments about the alternative leader that can be set in the settings.

**Comment by mcepl** [comment]
> You read the docs and play around with it before checking configuration options, right?

Except it is all there. In ``README.detailed``, I mean.

**Comment by mcepl** [comment]
> I don't know if 'bitter' is the appropriate word. ;)

No, it isn’t. Y’all too kind to me. But relatively speaking, these were the bitterest (?) conversations we had.

**Comment by xkpd3** [comment]
@mcpel: Yes indeed, but if you miss to read this line (https://github.com/vimoutliner/vimoutliner/blob/master/doc/votl.txt#L408) the whole documentation is missleading Below the leader ",," is assumed.

I think it can be mentioned, that the leader can be changed to ",,". But the documentation should reflect the default "\". So all the examples should contain "\" and not ",,", because this is the default.

And with default, I mean what works without changing anything after installing the plugin.

**Comment by mcepl** [comment]
#140 merged.
