### ISSUE TITLE
highlighting color changes only every other level

### ISSUE THREAD

**Issue by nilsbecker** [vimoutliner/vimoutliner#166]
see attached screenshot. i think the intended highlighting should be changing color on every new level?
i have the setting 
`  au FileType * set tabstop=2|set shiftwidth=2|set noexpandtab` in my .vimrc
<img width="1082" alt="Screen Shot 2020-01-09 at 11 11 33" src="https://user-images.githubusercontent.com/177614/72058919-437c6180-32d1-11ea-85a0-ab31522cc784.png">

**Comment by noelhenson** [comment]
That would make sense. The color encodings were set according to a 
tabstop being 4 characters wide. check your tabstop and shiftwidth 
first. It's been so long ago I don't remember exactly how the color 
encodings are triggered. They should be triggered on character locations 
(1, 4, 8, ...). Does it work if your tabstop and shiftwidth are set to 4?

Noel

**Comment by nilsbecker** [comment]
i set tabstob and shiftwidth to 4 each, and the indent for each level is now 4. but the coloring stays the same...

**Comment by nilsbecker** [comment]
ah wait! i tried a different colorscheme and the coloring is now every line. my default one is 'tender'. i guess it's a bug of the color scheme then?

**Comment by noelhenson** [comment]
It sounds like you nailed it.

I don't know the colorscheme "tender" I"m using an old, highly 
personalized version of VO.

Noel

**Comment by mcepl** [comment]
![Snímek z 2020-01-10 14-50-11](https://user-images.githubusercontent.com/198999/72157633-b280b580-33b8-11ea-8f49-884f16b637cf.png)

I don’t think there is anything wrong with what VO does (this is a standard [solarized8_high](https://github.com/lifepillar/vim-solarized8) colour scheme).

**Comment by mcepl** [comment]
Could you guy reproduce your problems with a standard colorscheme (just run ``:colorscheme default``)? If not, I will have to close this soon.

**Comment by nilsbecker** [comment]
the standard colorscheme works as intended. i think this can be closed.
