### ISSUE TITLE
Old bug in syntax/votl.vim

### ISSUE THREAD

**Issue by tlhall** [vimoutliner/vimoutliner#180]
Line 242 in syntax/votl.vim is:
	au BufNewFile,BufRead *.otl                     setf outliner
it should be:
	au BufNewFile,BufRead *.otl                     setf votl
I think this showed up with a newer version of VIM which corrected the execution order of plugin files.

**Comment by mcepl** [comment]
That’s nonsense. `setf` should not be run in `syntax/*` files at all. It should be run only in `ftdetect/votl.vim` and it already is.

**Comment by tlhall** [comment]
So a better fix (which I've tried and it works) is to just delete line 242.
