### ISSUE TITLE
Difficulty installing into gvim on Windows 7?

### ISSUE THREAD

**Issue by gilfra** [vimoutliner/vimoutliner#29]
Hello,

I've downloaded 0.3.6 and, as far as I can see, have precisely followed the instructions for installing on Windows as specified in 'README.detailed' and 'INSTALL.

However, when I create a new .otl file there is no indication that the installation has worked. 

Any help would really be appreciated.

Thanks, Gilbert

**Comment by z-hunter** [comment]
I have same problem on Windows 7.  Just installed VO to VIM with Vundle and it just doen't work.

> Also, when you open .otl file, could we get output of :set filetype?
filetype = conf

> :set filetype=vo_base
 Nothing changed.
