### ISSUE TITLE
http://www.vimoutliner.org/ is filled with spam

### ISSUE THREAD

**Issue by UnkindPartition** [vimoutliner/vimoutliner#36]
At least the link to it should be removed from the github page.

**Comment by josswright** [comment]
I've just installed vimoutliner and came across an old Google Groups discussion about the domain having been grabbed by spammers. I just noticed that it currently seems to be unregistered, so if you're still planning on grabbing it then this might be the moment.

**Comment by mcepl** [comment]
Taken on 2016-12-20T14:30:18Z by Cyrus the Great, LLC (https://www.pheenix.com). :(

**Comment by noelhenson** [comment]
Yep. A bot somewhere keyed on the mention of the domain and that it was 
available. Then it gets scooped up within minutes.

**Comment by josswright** [comment]
Sorry... I was tempted to snap it up when I saw it. I knew domain front running was a problem, but that's ridiculous. Someone set a calendar for this time next year, and make sure not to do a WHOIS query until the last minute!

Small comfort that it's cost the horrible company a little droplet of revenue to register it.
