### ISSUE TITLE
Add [ and ] to iskeyword

### ISSUE THREAD

**Issue by noelhenson** [vimoutliner/vimoutliner#87]
I believe we should add [ and ] to iskey word in the main VO plugin file. This makes it easier to use w and b for right/left movement when checkboxes and/or tags are present.
Note: this may impact magic.vim as it would change the behavior of <cword> and make it behave more like <cWORD>.

**Comment by mcepl** [comment]
@noelhenson , could you make a pull request for this, please?

**Comment by mcepl** [comment]
@noelhenson hopefully, this should be easy, shouldn't it? Could we get a pull request here, please?

**Comment by mcepl** [comment]
No reaction in many years, closing.
