### ISSUE TITLE
Question about ignoring leaves and branches [-]

### ISSUE THREAD

**Issue by noelhenson** [vimoutliner/vimoutliner#88]
I have been using [-], which is supported by votl_checkbox.vim to mark branches is 'ignored'. They still retain the states of the branch (except in the case of ignoring a leaf, in some cases). But it is an exception case when it comes to ,, commands.
Problem:
To use [-] one must manually replace [ _ ] or [X] with [-] and then execute a ,,cz. The same must be done to return the brach to a non-ignored state ([ _ ] or [X]).
Solution #1:
Leave it as it is. Nobody but Noel uses it anyway.
Solution #2:
Modify ,,cx to add [-] as an option. E.g. cycle through: [ _ ] [-] [X] in some specified order.
Solution #3:
Add an additional function and mapping to switch the state from not-ignored to ignored. Perhaps ,,ci would swap between [ _ ] or [X] and [-].
Thoughts?

**Comment by mcepl** [comment]
OK, so what's going on here? Who proposes to do what?

**Comment by noelhenson** [comment]
use the [-] to exclude a leaf/branch from inclusion in completion 
calculations. I believe the modification has already been done and 
tested. Documentation needs to be updated.

**Comment by mcepl** [comment]
@noelhenson So, this is only about missing docs?

**Comment by noelhenson** [comment]
Yes.

**Comment by mcepl** [comment]
@noelhenson Hmm, I am afraid there must be something wrong. I have here ``master`` branch of VO and yet when I press ``<localleader>ci`` nothing happens (``:map`` shows me it is not mapped even), and ``<localleader>cx`` doesn't go through ignoring leaf either (just flips between ``done`` and ``not-done`` state). Isn’t by chance your ``master`` different from what we have here?

**Comment by mcepl** [comment]
No reaction in two years. If you have actually interest in this, please, reopen.
