### ISSUE TITLE
Make a list of plugins that works well with Vimoutliner

### ISSUE THREAD

**Issue by jostber** [vimoutliner/vimoutliner#94]
It could be useful to have a list of vim plugins that works well with
VO and that might cover functionality in other outliners. Examples:

UTL.vim: Link text to URLs,other files or references
DOT.vim: Simple table of content 
Voom.vim: More advanced table of content
NrrwRgn.vim: Extract parts of outliner file to work on them

**Comment by mcepl** [comment]
@jostber  any progress on this?

**Comment by jostber** [comment]
On 27.09.15,10:36, Matěj Cepl wrote:
> @jostber  any progress on this?
> 

I have made a list here previously and will do a QA on this and upload to the site.

**Comment by mcepl** [comment]
@jostber Please, make a pull request. Thank you.

**Comment by mcepl** [comment]
No response, not that much important.
