### ISSUE TITLE
None of comma-comma commands are working

### ISSUE THREAD

**Issue by askhat** [vimoutliner/vimoutliner#98]
I've installed **vimoutliner** from Github via **pathogen**. My _.vimrc_'s first lines looks like this:

```
set nocompatible
filetype plugin indent off
execute pathogen#infect()
filetype plugin indent on
so .vimoutlinerrc
```

And _.vimoutlinerrc_ like this:

```
let maplocalleader = ',,'
```

But none of comma-comma commands not working.
I use **Ubuntu 14.10 x86**, **vim 7.4.273** and **vimoutliner 0.4.0**.

**Comment by mcepl** [comment]
> I never even thought of that. That could interfere with Vim interpreting
> the ',,'. Nice diagnostic work!

@noelhenson Shouldn't at least ``setlocal`` it then as a protection?
